In [6]:
import pandas as pd
import numpy as np

reviews = pd.read_csv('reviews.txt', header=None)
labels = pd.read_csv('labels.txt', header=None)

Y = (labels=='positive').astype(np.int_)
labels[:10]

In [8]:
len(Y) == len(labels)


True

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.random.shuffle(x)
x

array([9, 4, 1, 0, 2, 7, 6, 3, 5, 8])

In [22]:
import tensorflow as tf
import tflearn
from tflearn.data_utils import to_categorical


In [24]:
to_categorical(Y.values[:5],2)

array([[ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.]])